#!/usr/bin/env bash
echo "== sync"

# exit imediaely if any command returns a non zero status
set -e

# Check for bucket name
if [ -z "$1" ]; then
     echo "There needs to be a bucket name eg. ./buckey my-bucket-name."
     exit 1
fi

# Check for filename prefix name
if [ -z "$2" ]; then
     echo "There needs to be a filename prefix eg. ./buckey my-bucket-name my-filename."
     exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2

# where we store the files
OUTPUT_DIR="/tmp/s3-bash-scripts"

# remove folder if it already existsts
rm -r $OUTPUT_DIR

# create output folder
mkdir -p $OUTPUT_DIR


# generate a random number
# to determine how many files to create
NUM_FILES=$((RANDOM % 6 + 5))

# create files using a for loop
for ((i=1; i<=NUM_FILES; i++)); do
  touch "$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"

  echo "$NUM_FILES files created in $OUTPUT_DIR"
done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files